services:
  - type: web
    name: backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: YOLO_CONFIG_DIR
        value: /tmp/Ultralytics
    healthCheckPath: /docs

  - type: web
    name: frontend
    runtime: python
    plan: free
    buildCommand: pip install -r frontend/requirements.txt
    startCommand: streamlit run frontend/streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: BACKEND_URL
        fromService:
          name: backend
          type: web
          property: host